stg:
  ALARM_RECIPIENT_EMAIL: ""
  NAMESPACE_PREFIX: ${self:custom.namespace}
  NUMBER_OF_LAMBDA_VERSIONS_TO_RETAIN: 3
  NUMBER_OF_PREVIOUS_DEPLOYMENT_ARTIFACTS_TO_RETAIN: 1

prd:
  ALARM_RECIPIENT_EMAIL: ""
  NAMESPACE_PREFIX: ${self:custom.namespace}
  NUMBER_OF_LAMBDA_VERSIONS_TO_RETAIN: 5
  NUMBER_OF_PREVIOUS_DEPLOYMENT_ARTIFACTS_TO_RETAIN: 3
