Resources:

  SecretTwitterCredentials:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: ${self:provider.stage}/twitter/m1-money-supply-credentials
      Description: Twitter credentials
      Tags:
        - Key: Namespace
          Value: ${self:custom.namespace}
        - Key: Stage
          Value: ${self:provider.stage}

Outputs:

  SecretTwitterCredentialsARN:
    Description: Secret ARN for Twitter credentials
    Value:
      Ref: SecretTwitterCredentials
    Export:
      Name: ${self:provider.stage}-SecretTwitterCredentialsARN
